# Generated by Django 5.0 on 2023-12-14 06:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_email', models.CharField(max_length=255, unique=True)),
                ('emp_role', models.CharField(choices=[('hr', 'HR'), ('tl', 'Team Lead'), ('fd', 'Frontend Developer'), ('bd', 'Backend Developer'), ('fr', 'Full Stack Developer')], default='fd', max_length=2)),
                ('emp_phno', models.IntegerField(max_length=10, validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Phone number must be at least 10 digits.'), django.core.validators.MinValueValidator(limit_value=10, message='Phone number must be at least 10 digits.')])),
            ],
        ),
    ]
