# Generated by Django 5.0 on 2023-12-14 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_phno',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Phone number must be at least 10 digits.'), django.core.validators.MinValueValidator(limit_value=10, message='Phone number must be at least 10 digits.')]),
        ),
    ]
